### ISSUE TITLE
build fails with JDK 1.8

### ISSUE THREAD

**Issue by SubOptimal** [inspectIT/inspectIT#115]
The build with JDK 8 fails with 

```
* Where:
Build file '/home/suboptimal/develop/inspectIT/inspectit.server/inspectit.server.gradle' line: 114

* What went wrong:
Execution failed for task ':inspectit.server:schemagen-configurationUpdateSchemaCheck.xsd'.
> taskdef A class needed by class com.sun.tools.jxc.SchemaGenTask cannot be found: com/sun/mirror/apt/AnnotationProcessorFactory
```

Looks like a regression of [INSPECTIT-1958](https://inspectit-performance.atlassian.net/browse/INSPECTIT-1958).

**Comment by pbouillet** [comment]
Thanks for the issue! We already have another ticket for this: 
https://inspectit-performance.atlassian.net/browse/INSPECTIT-2090 

The thing is, even if we fix it now for gradle, it still isn't advised to build it with jdk 8 as many tests will fail. If you want to develop something for inspectIT, just go ahead to this documentation and you're ready:
https://inspectit-performance.atlassian.net/wiki/display/DEV/Development+Environment

On the other hand, if you want to test it out, just go with the official releases. The last (preview) one is 13 days ago and we plan to have the stable one out very very soon!

**Comment by SubOptimal** [comment]
Thanks for your answer. The second ticket I did not found during my search. Seems my search pattern was not fine grained enough.

**Comment by pbouillet** [comment]
No problem!

But why did you close the associated MR? We can still integrate this if the build is working then! My comment was just pointing more in the direction that from our side, the priority is not that high to fix it as you need anyway another JDK to develop against. But we can nevertheless go for your MR! Just a small remark: Could you prepend then in the commit message "INSPECTIT-2090: "? We enforce a referenced ticket to always have a clear association. Thanks :smile:

**Comment by SubOptimal** [comment]
I understood your comment that compiling with JDK 8 is not suggested for now. And to prevent others from doing some JDK 8 related development which probably would not be merged because of tailed tests I closed the PR.
Should I reopen it? So you would be able to use it for ticket INSPECTIT-2090.

**Comment by pbouillet** [comment]
It's not suggested, yes, but we can still fix this problem anyway.

Thus you can reopen it, rename the commit message and then we'll integrate it very soon :smile:

**Comment by SubOptimal** [comment]
OK. Have reopen it.

**Comment by thomasdarimont** [comment]
Hello,

I gave this a (2h) spin and can now build the project with Java 8 in a local (unpolished) branch.
What I had to do was:
- Upgrade Findbugs to 3.0
- Fix some findbug findings (due to better control flow analysis)
- Make the codebase aware of Java 8 (JavaVersion enum) 
- Improve the *ObjectSizes computations for changed Java 8 data structures (to fix the failing tests)
- Tweak the PDE build to work with Java 8

After that I could do a clean build on inspectIT with Java 8 (on linux x86_64) - but I haven't run it yet ;)
I try to polish my stuff and open a PR for it at the weekend.

Perhaps this can serve as a starting round for Java 8 Support.

Cheers,
Thomas

**Comment by ivansenic** [comment]
Hi Thomas,

You are pretty right the list seams fine and correct. Please push the updates. 

However, we have one big problem in moving to Java 8. In our release we deliver the correct JVM (so that memory calculations are correct) and that's currently 1.7.0_80. As you might know we are not allowed to ship with the Oracle JVMs due to the licensing problems. Thus, we are using the unofficial builds. However, for Java 8 there are still not all artifacts existing (check https://github.com/ojdkbuild/ojdkbuild and https://github.com/alexkasko/openjdk-unofficial-builds). So we are waiting for those.

Thus, your maybe we can not push your changes right away. Also I would say this is not only related to building with Java 8, but also running server and UI component on Java 8.

**Comment by ivansenic** [comment]
Hi @thomasdarimont ,

One thing. Regardless of Java 8 binaries that we need, we could still benefit from all your changes except the memory calculations. Maybe it makes more sense to exclude these for now. Sure CMR won't be able to run with Java 8, but at least we would fix all the issues regarding the build. What do you think?

**Comment by SubOptimal** [comment]
closed as related pull request [116](https://github.com/inspectIT/inspectIT/pull/116) has been merged.
