### ISSUE TITLE
visit ui from web

### ISSUE THREAD

**Issue by dragontree101** [inspectIT/inspectIT#154]
i install inspectIt in local for test, but i found ui is app(need to install)

i think if ui from app to web is better. 

can i visit ui in browser not in application?

**Comment by ivansenic** [comment]
@dragontree101 Unfortunately the Web UI is not available in inspectIT. We do plan to have some Kibana monitoring dashboards available soon, but that will be only for monitoring data. The diagnosis data will remain only accessible via the rich client. There is limited [Rest API](https://inspectit-performance.atlassian.net/wiki/display/DOC16/RESTful+Services) available as well, maybe that could help.

**Comment by stefansiegl** [comment]
@dragontree101 to add to @ivansenic. I understand the benefits of a webbased user interface and we already got quite a lot requests in this direction. We initially started with the decision of a rich client UI as we thought that this approach addresses the usecase of analysing an application the best.

For monitoring-focussed purposes a webbased user interface is - without a doubt - the better approach (primarily due to rollout reasons). As @ivansenic said we are thus planning to provide a nice Kibana based dashboarding that can be used for monitoring, but will - at least for the time - still stick with the rich client for detailed diagnosis.

The move to a complete webbased userinterface is associated with quite some effort. We intend to put this effort rather into the other new features of inspectIT. But you know this is an open source project. So if you or somebody else does have the time and need, please feel free to discuss with us how we can built an webbased-user interface together (we do have some nice ideas already).

**Comment by dragontree101** [comment]
@ivansenic  @stefansiegl   
thanks very much :)
