### ISSUE TITLE
Tomcat agent has been register as a new agent after system error.

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#263]
Hi

I want to report an issue of InspectIT registration.
One of our Tomcat 8.0.41 server which was monitored by InspectIT has been shutdown unexpectedly because of system error at 4/21 (UTC+8) about 5:00 PM.
The strange thing is that later when we startup Tomcat at about 5:00, it has been registered as another agent instead of previous one in CMR.

<img src="https://cloud.githubusercontent.com/assets/1283378/25328546/d407af3a-290a-11e7-9d0b-73154d1bd0df.png" width="500" height="600" />

It's disappointed that we didn't found anything which looks useful to solve this problem in [log files][log files].
Since we are not allowed to replace this machine with another in recent months, I'd like to know what should we do to ensure that metrics collected from agent after hardware failure will be aggregate with previous data?

[log files]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuQXI0eldyLU02RTQ?usp=sharing
[InspectIT deployments]: https://docs.google.com/spreadsheets/d/1uPVIjaXcsi9pcvb_6ZH8zHaqGevd5B9beUt_yRilzJw/edit?usp=sharing "InspectIT deployments"

**Comment by pbouillet** [comment]
Hi @youjenli ,

the default for the agent registration is that they are seperated by their IP addresses and their agent name. Thus what you see here is that one of the IP addresses has been changed of this machine and that's why it shows up as a different one. You can configure this behavior to just use the agent name:
https://inspectit-performance.atlassian.net/wiki/display/DOC17/IP+based+agent+registration

Beware: Before doing this, ensure that one of those two agents is deleted from the system. Otherwise the server will throw an error upon registration. You can delete an agent if it's not connected and just right-click on it and click on "Delete Agent".

Hope this helps!

**Comment by youjenli** [comment]
Does InspectIT identify clients base on IPv6 address?
I found out that IPv6 address of our host has been change from `0:0:0:0:0:0:0:1%lo0:6` to `0:0:0:0:0:0:0:1%lo0:2` after it restart. And we never use IPv6 address to locate that host.

**Comment by pbouillet** [comment]
Yes it does. All IPv4 and v6 addresses are included for the check.

**Comment by youjenli** [comment]
Thanks!
I will see what I should do to fix this problem.
