### ISSUE TITLE
Method Invocation Tracking

### ISSUE THREAD

**Issue by Wafflemon** [inspectIT/inspectIT#269]
Hello,

Is it possible with inspectIT to track a method's invocation and exit? I'm interested in being able to track that sort of information on the fly to quickly test the performance of a new feature or whatever else. It'd be useful to even track the method invocation itself and see a timeline of how often it's called. Really, I'm interested in the time deltas of the methods (for blocking methods) and the frequency a method is called. The big picture is good enough, but more data on a thread by thread basis would be potentially useful.

**Comment by ivansenic** [comment]
Hi @WaffleTime,

Sorry for late reply, we are all on the long weekend here due to the 1st May holidays..

Sure method invocation information can be obtained by our most used sensor - Timer sensor. Just apply it to the method of interest and you will get duration and invocation count statistics. For more data on thread it self, it's also useful to use the [Start invocation](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Sensor+assignments+configuration#Sensorassignmentsconfiguration-Startsinvocation) option in Timer sensor configuration. This way you also get invocation sequences that wrap all the sub-method calls from this point into a trace-based representation.
