### ISSUE TITLE
what is installation step for Inspectit APM tool on Linux Machine

### ISSUE THREAD

**Issue by prashantnitt07** [inspectIT/inspectIT#367]
hi ,
please suggest to me , what is installation step for InspectiT apm tool on Linux Machine

1. UI  installation step 
3. CRM installation step

**Comment by prashantnitt07** [comment]
please help for setup InpectIT APM on linux server.

**Comment by ivansenic** [comment]
For the linux server you just need to install the CMR there.. It's simple as downloading the CMR pack (https://github.com/inspectIT/inspectIT/releases/download/1.8.4.98/inspectit-cmr.linux.x64-1.8.4.98.zip) and unzipping it. The you start it by running the `./startup.sh`. That's all. The logs should print the `CMR started in xyz seconds`.

Basically it should be something like:

```
mkdir /opt/inspectit
cd /opt/inspectit
wget https://github.com/inspectIT/inspectIT/releases/download/1.8.4.98/inspectit-cmr.linux.x64-1.8.4.98.zip
unzip inspectit-cmr.linux.x64-1.8.4.98.zip
cd CMR/
nohup ./startup.sh &
```

After that you install the inspectIT UI on your Desktop machine. Go to Add repository (+) and enter IP of the machine where the CMR is installed in order to connect to the CMR. That's it, should be easy.

**Comment by ivansenic** [comment]
Closing as there s no real issue here imo.
