### ISSUE TITLE
Instrumentation dependencies question

### ISSUE THREAD

**Issue by Wafflemon** [inspectIT/inspectIT#392]
I've been looking into adding Thrift instrumentation (I've successfully added a CompletableFuture sensor in order to learn how to add instrumentation.) InspectIT's current instrumentation seems to utilize reflection. I would guess that this is done to prevent the need for dependencies, but I'm not sure what the goal is. 

I'm currently looking at an [opentracing Thrift library](https://github.com/opentracing-contrib/java-thrift) that I was going to use as a guide to add instrumentation to InspectIT. However, the instrumentation is going to require a few Thrift classes to be decorated. I could decorate the Thrift classes using a [Proxy](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Proxy.html) and that would eliminate the need for a dependency. Is that the preferred approach to this situation for InspectIT?

**Comment by ivansenic** [comment]
Hi @Wafflemon ,

About the dependencies and reflection. That's the only possibility we have, we can not depend on the specific version of the lib dependencies. The reason is the following: all the inspectIT dependencies are loaded with inspectIT class-loader. This way any operation you would do on the target class loaded by the application class loader would resolve in the `ClassCastException` as classes in Java are not equal if loaded by different class loaders. If we would load inspectIT dependencies with the boot-class loader (possible), then we would basically force the application to use our dependencies. So if we are on example-lib-1.1 and application is using example-lib-1.3, then as we would push v1.1 to the boot class loader, we are screwing the version that application expects.

This is why we developed our own proxy mechanism in order to proxy classes that are loaded by the application class loader. This is often needed, especially when you need a delegate or something similar. Easy example on how to do this is shown in our [proxies for the Jetty and HttpClient](https://github.com/inspectIT/inspectIT/tree/master/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/proxy). The initialization of the proxy is shown in [CloseableHttpAsyncClientHook](https://github.com/inspectIT/inspectIT/blob/fbadd7d574a0ea36a695bbd5d8629ae668ad6525/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/special/CloseableHttpAsyncClientHook.java):

```
FutureCallbackProxy proxy = new FutureCallbackProxy(originalCallback, spanStoreAdapter);
Object newProxy = runtimeLinker.createProxy(FutureCallbackProxy.class, proxy, object.getClass().getClassLoader());
``` 

Note that class loader must be one that loaded the class you want to proxy.

Hope this helps..

**Comment by Wafflemon** [comment]
Thanks for the information!
