### ISSUE TITLE
SQL Query Statement truncated if the statement length greater than 1001

### ISSUE THREAD

**Issue by mygithubwork** [inspectIT/inspectIT#393]
Spring application using Hibernate as ORM, if the SQL statement greater than 1001, InspectIT Client SQL Show All statement shows sql with 1004 character but no way to get complete statement. please provide a solution to view complete sql statement
![sqlstatementissue](https://user-images.githubusercontent.com/5734199/42678560-d9aa9e7e-86b1-11e8-919e-82976be9b327.jpg)

**Comment by mariusoe** [comment]
Hello,

this is a safty-feature in order to protect the agent that it will not collect too much data, e.g. when collecting SQL statements. By default, it collects only the first 1000 characters of a SQL statement but the limit can be changed in the environment settings. 

Here is an explanation how the limit (of the JDBC statement sensor in your case) can be changed: https://inspectit-performance.atlassian.net/wiki/spaces/DOC18/pages/93009271/Environment+configuration

**Comment by ivansenic** [comment]
Use `Sensor Pptions` in Environment config to unlimit the captured strings per sensor.

![Sensor options](https://inspectit-performance.atlassian.net/wiki/download/thumbnails/93009271/sensorOptions.png?version=1&modificationDate=1464354423532&cacheVersion=1&api=v2&effects=drop-shadow&width=486&height=400)

Closing as the configuration option exists.
