### ISSUE TITLE
Java 8 Agent Upgrade

### ISSUE THREAD

**Issue by Wafflemon** [inspectIT/inspectIT#395]
Hello,

I currently have a CompletableFuture sensor integrated into InspectIT. However, the CompletableFuture sensor requires the inspectIT agent to upgrade to Java 8. If I was to create a pull request, then would the inspectIT team be interested in the CompletableFuture sensor and upgrading the agent to Java 8 at all? I still need to get approval to submit the pull request, but we're willing to contribute a CompletableFuture and Thrift sensor.

**Comment by ivansenic** [comment]
I don't think we are willing to move to Java 8. The reason is simple, we want to support as many people as we can. There is a bunch of application still running on Java 7 & 6, believe me.  And those people have way fewer options for the open source Java APM that the ones developing on 8+. If you look into other open source APM tools, they mainly support only Java 8+ applications.

We are on the other hand we are definitely planning to move to Java 7 soon, due to some changes we are looking forward to implementing.

You can still proxy the `CompletableFeture` as any other class as described in the #392

**Comment by Wafflemon** [comment]
You're right, it's best to support as many versions as possible for this kind of a tool. I'll try to rethink my approach.
